/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lsftugnsgnwhlvghfrrx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzZnR1Z25zZ253aGx2Z2hmcnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2NDcwMzIsImV4cCI6MjA4NzIyMzAzMn0.MUv6VKWqbV2Bz-B35M76k3TMLu2jM-wUECkIDd3mVKc"